[package]
name = "paa5100je-pmw3901"
version = "0.1.0"
edition = "2021"
authors = ["Pete Kubiak <peter.kubiak@dyson.com>"]

[dependencies]
thiserror = { version = "2.0.11", default-features = false }
embedded-hal-async = "*"
defmt = "0.3.10"
