---
name: Continuous Build
on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  All_Targets:
    name: All Targets Build (src)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #TODO: Add Windows (See Issue) https://github.com/dysonltd/paa5100je-pwm3901/issues/8
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-targets --all-features 

  Examples:
    name: ESP32C6 Example
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #TODO: Add Windows (See Issue) https://github.com/dysonltd/paa5100je-pwm3901/issues/8
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd examples/esp32c6
          cargo build --all-features
